
server:
#  port: ${vcap.application.port:9088}
   port: 9088

spring:
  jpa:
    generate-ddl: true


eureka:
  client:
    serviceUrl:
#      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
       defaultZone: http://macusers-MacBook-Pro.local:9761/eureka/
